version: "3.9"
services:
  api:
    build: .
    container_name: menu-api
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    environment:
      APP_KEY: base64:$(php artisan key:generate --show)
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      CACHE_STORE: file
  queue:
    build: .
    container_name: laravel_queue
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - .:/var/www/html